name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"] # Or "main" if that's your branch name

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # This should point to your build folder (usually 'dist' for Vite or 'build' for React)
          path: ./dist
      - name: Deploy
        uses: actions/deploy-pages@v4